FROM python:3.7-slim

WORKDIR /app

COPY ./backend/api_foodgram .

RUN apt-get update \
    && apt-get -y install libpq-dev gcc \
    && pip install psycopg2

RUN pip3 install -r requirements.txt --no-cache-dir

CMD ["gunicorn", "api_foodgram.wsgi:application", "--bind", "0:8000" ]